"""
Module: ollama_provider
Purpose: Implements integration with a local Ollama instance.
Ollama runs LLMs locally and exposes a simple REST API. This provider uses standard
HTTP requests to interact with that API to generate responses.
"""

import requests
import json
from .base_llm import BaseLLM
from config.settings import OLLAMA_URL, OLLAMA_MODEL, OLLAMA_TIMEOUT

class OllamaProvider(BaseLLM):
    """
    Provider class for interacting with locally hosted Ollama models.
    Inherits from BaseLLM, ensuring it implements the `generate` method.
    """
    
    def __init__(self):
        """
        Initializes the Ollama provider by setting up the target endpoint URL
        and selecting the model based on the application's configuration.
        """
        # Ensure the URL is correctly formatted by stripping trailing slashes 
        # and appending the specific generate endpoint
        self.url = f"{OLLAMA_URL.rstrip('/')}/api/generate"
        self.model = OLLAMA_MODEL

    def generate(self, prompt: str) -> str:
        """
        Sends a POST request to the Ollama API with the prompt.
        
        Args:
            prompt (str): The structured prompt containing code and instructions.
            
        Returns:
            str: The raw JSON string returned by the Ollama model.
        """
        # Construct the JSON payload for the API request
        payload = {
            "model": self.model,
            "prompt": prompt,
            "stream": False,  # We want the complete response at once, not streaming chunks
            "format": "json"  # Instructs Ollama to force the model to output valid JSON
        }
        
        try:
            # Make the HTTP POST request to the Ollama instance with the configured timeout
            response = requests.post(self.url, json=payload, timeout=OLLAMA_TIMEOUT)
            
            # Raise an HTTPError if the HTTP request returned an unsuccessful status code (e.g. 404 or 500)
            response.raise_for_status()
            
            # Parse the JSON response from the server
            data = response.json()
            
            # Extract and return the actual text generated by the model
            return data.get("response", "")
        except requests.exceptions.RequestException as e:
            # Catch network errors, timeouts, or bad HTTP status codes
            print(f"Error calling Ollama API: {e}")
            raise
