"""
This module defines the Pydantic data models (schemas) used to structure the JSON responses 
generated by the Language Learning Models (LLMs) in the CodeExplain application.

By using Pydantic, we ensure that the output from the LLMs is strongly typed, validated, 
and adheres to a predictable format that the application can easily parse and display to the user.
"""

from typing import List
from pydantic import BaseModel, Field

class LineExplanation(BaseModel):
    """
    Schema for explaining a single line of code.
    Used as part of the 'line_by_line' breakdown in the main response.
    """
    line_number: int = Field(description="The 1-based index of the line in the code snippet.")
    code: str = Field(description="The actual code present on this line.")
    explanation: str = Field(description="A clear, concise explanation of what this specific line does.")

class ResponseSchema(BaseModel):
    """
    The main schema for the code explanation response.
    This defines the exact structure we expect the LLM to return when asked to explain a piece of code.
    """
    detected_language: str = Field(description="The programming language of the code, auto-detected if not specified.")
    summary: str = Field(description="A brief summary of what the code does.")
    layman_explanation: str = Field(description="A layman explanation of the code for beginners.")
    line_by_line: List[LineExplanation] = Field(description="Line-by-line breakdown of the code.")
    time_complexity: str = Field(description="Time complexity analysis (Best, Average, Worst).")
    space_complexity: str = Field(description="Space complexity analysis.")
    improvements: List[str] = Field(description="Maximum 5 meaningful suggestions for improvement.")
    translation: str = Field(description="Translation of the explanation into the selected language (if requested).")

class QuizOption(BaseModel):
    """
    Schema for a single multiple-choice option within a quiz question.
    """
    text: str = Field(description="The text of the option.")
    is_correct: bool = Field(description="Whether this option is the correct answer.")
    explanation: str = Field(description="A layman explanation of why this option is correct or incorrect.")

class QuizQuestion(BaseModel):
    """
    Schema for a single comprehension question related to the explained code.
    Contains the question text and a list of possible options.
    """
    question: str = Field(description="The comprehension question related to the code snippet.")
    options: List[QuizOption] = Field(description="4 clickable options for this question.")

class QuizSchema(BaseModel):
    """
    The main schema for the generated quiz.
    This defines the structure of the quiz JSON returned by the LLM, consisting of a list of questions.
    """
    questions: List[QuizQuestion] = Field(description="Exactly 3 comprehension questions.")
